name = Island Archives Main Page Sticky Header
description = Island Archives Main Page Template.
preview = preview.png
template = island_archives_stickyheader

; ========================================
; Regions
; ========================================
regions[navigation] = Navigation
regions[header] = Header
regions[search_dropdown] = Search Dropdown Panel
regions[help] = Help
regions[content] = Content
regions[sidebar_first] = First Sidebar
regions[footer] = Footer

; Stylesheets
;stylesheets[all][] = css/layouts/island_archives_main/island_archives_main.layout.css
;stylesheets[all][] = css/layouts/island_archives_main/island_archives_main.layout.no-query.css
