name = Island Archives Main Page Template
description = Island Archives Main Page Template.
preview = preview.png
template = island_archives_main

; Regions
regions[branding]       = Branding
regions[navigation]     = Navigation bar
regions[header]         = Header
regions[hero]           = Hero
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/island_archives_main/island_archives_main.layout.css
;stylesheets[all][] = css/layouts/island_archives_main/island_archives_main.layout.no-query.css
