name = Nekkid
description = A stack of regions with no styles or layout.
preview = preview.png
template = nekkid-layout

; Regions
regions[branding]       = Branding
regions[navigation]     = Navigation bar
regions[header]         = Header
regions[hero]           = Hero
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/nekkid/nekkid.layout.css
;stylesheets[all][] = css/layouts/nekkid/nekkid.layout.no-query.css
